"""empty message

Revision ID: 049dcf2d8a7d
Revises: cdd73c65f356
Create Date: 2025-09-09 17:57:41.932441

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '049dcf2d8a7d'
down_revision = 'cdd73c65f356'
branch_labels = None
depends_on = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		'gifts',
		'price',
		existing_type=sa.REAL(),
		type_=sa.Float(precision=10,
		asdecimal=2),
		existing_nullable=False
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		'gifts',
		'price',
		existing_type=sa.Float(precision=10,
		asdecimal=2),
		type_=sa.REAL(),
		existing_nullable=False
	)
	# ### end Alembic commands ###
