"""add last_email_at

Revision ID: 2e295b26ddaa
Revises: d12cab3068cb
Create Date: 2025-05-15 12:21:15.073918

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2e295b26ddaa'
down_revision = 'd12cab3068cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		'gifts',
		'price',
		existing_type=sa.REAL(),
		type_=sa.Float(precision=10,
		asdecimal=2),
		existing_nullable=False
	)
	op.add_column('users', sa.Column('last_email_at', sa.DateTime(), nullable=True))
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column('users', 'last_email_at')
	op.alter_column(
		'gifts',
		'price',
		existing_type=sa.Float(precision=10,
		asdecimal=2),
		type_=sa.REAL(),
		existing_nullable=False
	)
	# ### end Alembic commands ###
