"""empty message

Revision ID: 97f025d12d36
Revises: 049dcf2d8a7d
Create Date: 2025-09-23 16:26:57.499105

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '97f025d12d36'
down_revision = '049dcf2d8a7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		'gifts',
		'price',
		existing_type=sa.REAL(),
		type_=sa.Float(precision=10,
		asdecimal=2),
		existing_nullable=False
	)
	op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='false'))
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column('users', 'is_admin')
	op.alter_column(
		'gifts',
		'price',
		existing_type=sa.Float(precision=10,
		asdecimal=2),
		type_=sa.REAL(),
		existing_nullable=False
	)
	# ### end Alembic commands ###
