"""empty message

Revision ID: f198743da885
Revises: 
Create Date: 2025-02-12 19:11:45.694940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f198743da885'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('profile_pic', sa.String(length=250), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('is_hidden_bd', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('friend_requests',
    sa.Column('status', sa.Enum('sent', 'accepted', 'rejected', name='status'), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('rejected_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rejected_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_friend_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('wishlists',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gifts',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('img', sa.String(length=250), nullable=True),
    sa.Column('price', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('link_url', sa.String(length=200), nullable=False),
    sa.Column('is_priority', sa.Boolean(), nullable=False),
    sa.Column('booked_by_id', sa.Integer(), nullable=True),
    sa.Column('wishlist_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booked_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishlist_users_association',
    sa.Column('wishlist_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist_users_association')
    op.drop_table('gifts')
    op.drop_table('wishlists')
    op.drop_table('user_friend_association')
    op.drop_table('friend_requests')
    op.drop_table('users')
    # ### end Alembic commands ###
