version: '3.8'

services:
  fastapi: 
    container_name: fastapi-vist
    build: .
    depends_on:
      - pgdb
    command: python main.py
    volumes:
      - .:/usr/src/app
    ports:
      - 8085:8000
    restart: always
    env_file:
      - .env

  pgdb:
    container_name: vist-postgres
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: always
    env_file:
      - .env